In [3]:
orders = [ ["34587", "Learning Python, Mark Lutz", 4, 40.95], ["98762", "Programming Python, Mark Lutz", 5, 56.80], ["77226", "Head First Python, Paul Barry", 3,32.95],
           ["88112", "Einführung in Python3, Bernd Klein", 3, 24.99]]

min_order = 100
invoice_totals = list(map(lambda x: x if x[1] >= min_order else (x[0], x[1] + 10), map(lambda x: (x[0],x[2] * x[3]), orders)))

print(invoice_totals)

[('34587', 163.8), ('98762', 284.0), ('77226', 108.85000000000001), ('88112', 84.97)]


In [41]:
import functools
functools.reduce(lambda x,y: x+y, range(150))

11175

In [42]:
a = [1,2,3,4]
b = [17,12,11,10]
c = [-1,-4,5,9]

print(list(map(lambda x,y:x+y, a,b)))

print(list(map(lambda x,y,z:x+y+z, a,b,c)))

print(list(map(lambda x,y,z : 2.5*x + 2*y - z, a,b,c)))

[18, 14, 14, 14]
[17, 10, 19, 23]
[37.5, 33.0, 24.5, 21.0]


In [50]:
def fib(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fib(n-1) + fib(n-2)

def memoize(f):
    memo = {}
    def helper(x):
        if x not in memo:            
            memo[x] = f(x)
            print(memo.keys())
            print(memo.values())
            print(memo[x])
        return memo[x]
    return helper

fib = memoize(fib)
print(type(fib))
print(fib(40))

<class 'function'>
dict_keys([1])
dict_values([1])
1
dict_keys([0, 1])
dict_values([0, 1])
0
dict_keys([0, 1, 2])
dict_values([0, 1, 1])
1
dict_keys([0, 1, 2, 3])
dict_values([0, 1, 1, 2])
2
dict_keys([0, 1, 2, 3, 4])
dict_values([0, 1, 1, 2, 3])
3
dict_keys([0, 1, 2, 3, 4, 5])
dict_values([0, 1, 1, 2, 3, 5])
5
dict_keys([0, 1, 2, 3, 4, 5, 6])
dict_values([0, 1, 1, 2, 3, 5, 8])
8
dict_keys([0, 1, 2, 3, 4, 5, 6, 7])
dict_values([0, 1, 1, 2, 3, 5, 8, 13])
13
dict_keys([0, 1, 2, 3, 4, 5, 6, 7, 8])
dict_values([0, 1, 1, 2, 3, 5, 8, 13, 21])
21
dict_keys([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
dict_values([0, 1, 1, 2, 3, 5, 8, 13, 21, 34])
34
dict_keys([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
dict_values([0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55])
55
dict_keys([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])
dict_values([0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89])
89
dict_keys([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
dict_values([0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144])
144
dict_keys([0, 1, 2, 3, 4, 5, 6, 7, 8

In [52]:
class Memoize:
    def __init__(self, fn):
        self.fn = fn
        self.memo = {}
    def __call__(self, *args):
        if args not in self.memo:
            self.memo[args] = self.fn(*args)
        return self.memo[args]

@Memoize
def fib(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fib(n-1) + fib(n-2)
fib(40)

102334155

In [65]:
def factors_set():
    factors_set = ( (i, j, k, l, m) for i in [-2, 0, 2] 
                          for j in [-2, 0, 2]
                          for k in [-2, 0, 2]
                          for l in [-2, 0, 2]
                          for m in [-2, 0, 2])
    for factor in factors_set:
        yield factor

def memoize(f):
    results = {}
    def helper(n):
        if n not in results:
            results[n] = f(n)
        return results[n]
    return helper

@memoize
def linear_combination(n):
    """ returns the tuple (i,j,k,l) satisfying
        n = i*1 + j*3 + k*9 + l*27      """
    weighs = (1,3,9,27,236)
      
    for factors in factors_set():
       sum = 0
       for i in range(len(factors)):
          sum += factors[i] * weighs[i]
       if sum == n:
          return factors

linear_combination(4)

(-2, 2, 0, 0, 0)

In [67]:
from math import sin, cos, tan, pi

def map_functions(x, functions):
     """ map an iterable of functions on the the object x """
     res = []
     for func in functions:
         res.append(func(x))
     return res

def map_functions(x, functions):
     return [ func(x) for func in functions ]

family_of_functions = (sin, cos, tan)
print(map_functions(pi, family_of_functions))

[1.2246467991473532e-16, -1.0, -1.2246467991473532e-16]


In [75]:
fibonacci = [0,1,1,2,3,5,8,13,21,34,55,89,144,243]
odd_numbers = list(filter(lambda x: x % 2, fibonacci))
print(odd_numbers)
even_numbers = list(filter(lambda x: x%2 ==0, fibonacci))
print(even_numbers)

[1, 1, 3, 5, 13, 21, 55, 89, 243]
[0, 2, 8, 34, 144]


In [113]:
[(x,y,z) for x in range(1,210) for y in range(x,210) for z in range(y,210) if x**3 + y**3 == z**3]

[]

In [97]:
import numpy as np
a=numpy.matrix('1 0 5;0 1 4.5;7 8 1')
b=numpy.matrix('1 2 -4;3 4 -3;4 9 -5')
print(a.nbytes)
a+b

72


matrix([[  2. ,   2. ,   1. ],
        [  3. ,   5. ,   1.5],
        [ 11. ,  17. ,  -4. ]])

In [102]:
x = np.array([-1, 0, 1])
y = np.array([-2, 0, 2])
X, Y = np.meshgrid(x, y)
print(X)
print(Y)
Z = (X + Y) ** 2
print(Z)

[[-1  0  1]
 [-1  0  1]
 [-1  0  1]]
[[-2 -2 -2]
 [ 0  0  0]
 [ 2  2  2]]
[[9 4 1]
 [1 0 1]
 [1 4 9]]


In [112]:
def f(n,m):
             res = n + 10 * m
             return res
A = np.fromfunction(f, (8, 10), dtype=int)
A.shape
print(A)
A[:, :-2]

[[ 0 10 20 30 40 50 60 70 80 90]
 [ 1 11 21 31 41 51 61 71 81 91]
 [ 2 12 22 32 42 52 62 72 82 92]
 [ 3 13 23 33 43 53 63 73 83 93]
 [ 4 14 24 34 44 54 64 74 84 94]
 [ 5 15 25 35 45 55 65 75 85 95]
 [ 6 16 26 36 46 56 66 76 86 96]
 [ 7 17 27 37 47 57 67 77 87 97]]


array([[ 0, 10, 20, 30, 40, 50, 60, 70],
       [ 1, 11, 21, 31, 41, 51, 61, 71],
       [ 2, 12, 22, 32, 42, 52, 62, 72],
       [ 3, 13, 23, 33, 43, 53, 63, 73],
       [ 4, 14, 24, 34, 44, 54, 64, 74],
       [ 5, 15, 25, 35, 45, 55, 65, 75],
       [ 6, 16, 26, 36, 46, 56, 66, 76],
       [ 7, 17, 27, 37, 47, 57, 67, 77]])